# Generated by Django 2.2.4 on 2020-02-13 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('application_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_of_application', models.DateField(default=datetime.datetime(2020, 2, 13, 12, 10, 4, 169892, tzinfo=utc))),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC-CL', 'OBC Creamy Layer'), ('OBC-NCL', 'OBC Non Creamy Layer'), ('GEN-PWD', 'General Person with disabilties'), ('OBC-CL-PWD', 'OBC Creamy Layer Person with disabilites'), ('OBC-NCL-PWD', 'OBC Non Creamy Layer Person with disabilites'), ('SC-PWD', 'SC person with disabilites'), ('ST-PWD', 'ST person with disabilites')], max_length=25)),
                ('reservation', models.CharField(blank=True, choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC-NCL', 'OBC Non Creamy Layer'), ('PWD', 'General Person with disabilties'), ('SERVICE', 'Ex-Service Man'), ('GEN-ECO', 'General Category Economically Weaker Sections')], max_length=25, null=True)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_and_research_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('sole_instructor', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('developer_of_course', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('role', models.CharField(max_length=200)),
                ('pay_scale', models.IntegerField()),
                ('emoluments', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_and_research_detail', to='recruitment.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Profession_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('role', models.CharField(max_length=250)),
                ('pay_scale', models.IntegerField()),
                ('emoluments', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_detail', to='recruitment.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_university', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Pursuing', 'Pursuing')], max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('division', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=10)),
                ('percentage', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_detail', to='recruitment.Applicant')),
            ],
        ),
    ]
