# Generated by Django 3.2.3 on 2021-06-08 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd',
            name='supporting_documents',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 5, 55, 58, 901407, tzinfo=utc)),
        ),
    ]
