# Generated by Django 2.2.4 on 2020-02-13 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='academic_detail',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='date_of_application',
        ),
        migrations.AddField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 13, 39, 45, 504881, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.CharField(default='CSE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='post',
            field=models.CharField(default='PROF', max_length=100),
            preserve_default=False,
        ),
    ]
