# Generated by Django 3.2.3 on 2021-06-06 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 16, 29, 15, 597835, tzinfo=utc)),
        ),
    ]
