<<<<<<< HEAD:recruitment/migrations/0002_auto_20210508_1203.py
# Generated by Django 2.2.20 on 2021-05-08 06:33
=======
# Generated by Django 2.2.20 on 2021-05-08 06:30
>>>>>>> test-front:recruitment/migrations/0002_auto_20210508_1200.py

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
<<<<<<< HEAD:recruitment/migrations/0002_auto_20210508_1203.py
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 6, 33, 27, 726335, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 6, 30, 45, 495555, tzinfo=utc)),
>>>>>>> test-front:recruitment/migrations/0002_auto_20210508_1200.py
        ),
        migrations.AlterField(
            model_name='summary',
            name='defence_date',
<<<<<<< HEAD:recruitment/migrations/0002_auto_20210508_1203.py
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 6, 33, 27, 735699, tzinfo=utc)),
=======
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 6, 30, 45, 505192, tzinfo=utc)),
>>>>>>> test-front:recruitment/migrations/0002_auto_20210508_1200.py
        ),
    ]
