# Generated by Django 2.2.20 on 2021-06-15 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import recruitment.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='receipt',
            field=models.FileField(default=0, upload_to=recruitment.models.handle_uploaded),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 11, 13, 29, 157087, tzinfo=utc)),
        ),
    ]
