# Generated by Django 2.2.4 on 2020-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC-CL', 'OBC Creamy Layer'), ('OBC-NCL', 'OBC Non Creamy Layer'), ('GEN-PWD', 'General Person with disabilties'), ('OBC-CL-PWD', 'OBC Creamy Layer Person with disabilites'), ('OBC-NCL-PWD', 'OBC Non Creamy Layer Person with disabilites'), ('SC-PWD', 'SC person with disabilites'), ('ST-PWD', 'ST person with disabilites')], default='None', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='current_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='permanent_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='reservation',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC-NCL', 'OBC Non Creamy Layer'), ('PWD', 'General Person with disabilties'), ('SERVICE', 'Ex-Service Man'), ('GEN-ECO', 'General Category Economically Weaker Sections')], max_length=25, null=True),
        ),
    ]
