# Generated by Django 2.2.20 on 2021-06-08 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 6, 28, 17, 86725, tzinfo=utc)),
        ),
    ]
