# Generated by Django 2.2.4 on 2020-02-19 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 6, 20, 52, 522166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_and_research_details', to='recruitment.Applicant'),
        ),
    ]
