# Generated by Django 2.2.4 on 2020-02-19 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20200219_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession_detail',
            new_name='Professional_detail',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 6, 36, 8, 835004, tzinfo=utc)),
        ),
    ]
