# Generated by Django 3.2.3 on 2021-06-06 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_applicant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='awards_and_recognition',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 16, 40, 31, 784327, tzinfo=utc)),
        ),
    ]
