# Generated by Django 3.2.3 on 2021-06-08 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210608_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherinfo',
            name='college_punishment',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 6, 11, 36, 355965, tzinfo=utc)),
        ),
    ]
