# Generated by Django 2.2.4 on 2020-02-13 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20200213_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_detail',
            name='division',
        ),
        migrations.AlterField(
            model_name='academic_detail',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('ResultAwaited', 'ResultAwaited'), ('FinalAwaited', 'FinalAwaited'), ('Ongoing', 'Ongoing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 14, 50, 8, 803028, tzinfo=utc)),
        ),
    ]
