# Generated by Django 2.2.20 on 2021-05-28 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210512_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 28, 18, 52, 47, 585454, tzinfo=utc)),
        ),
    ]
