# Generated by Django 2.2.20 on 2021-04-28 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210426_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrative_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_number', models.CharField(max_length=10)),
                ('ongoing', models.TextField()),
                ('completed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sponsored_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_number', models.CharField(max_length=10)),
                ('ongoing', models.TextField()),
                ('completed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing_phd', models.TextField()),
                ('completed_phd', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 6, 47, 23, 269817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='general',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 6, 47, 23, 272807, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Academic_detail',
        ),
        migrations.AddField(
            model_name='thesis',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thesis', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='sponsored_project',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_project', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='experiments',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experiments', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='administrative_details',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_details', to='recruitment.Applicant'),
        ),
    ]
