# Generated by Django 2.2.24 on 2021-08-05 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210615_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 9, 33, 5, 430553, tzinfo=utc)),
        ),
    ]
