# Generated by Django 2.2.4 on 2020-02-13 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20200213_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 13, 14, 57, 37, 543018, tzinfo=utc)),
        ),
    ]
