# Generated by Django 2.2.24 on 2021-08-08 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20210805_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 10, 28, 44, 639192, tzinfo=utc)),
        ),
    ]
