# Generated by Django 2.2.20 on 2021-05-28 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20210529_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 28, 19, 33, 45, 676285, tzinfo=utc)),
        ),
    ]
