# Generated by Django 2.2.20 on 2021-04-28 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20210428_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 7, 9, 17, 560859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='general',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 7, 9, 17, 565878, tzinfo=utc)),
        ),
    ]
