# Generated by Django 2.2.20 on 2021-05-09 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20210509_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 16, 28, 52, 729834, tzinfo=utc)),
        ),
    ]
