# Generated by Django 2.2.4 on 2020-02-19 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20200219_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_detail',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 19, 33, 38, 493965, tzinfo=utc)),
        ),
    ]
