# Generated by Django 2.2.4 on 2020-02-21 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20200220_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 8, 50, 34, 905374, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_and_research_details', to='recruitment.Applicant'),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='co_investigators',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='developer_of_course',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='guide',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='level',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='name_of_body',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='name_of_institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='name_of_student',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='sole_instructor',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='status_of_membership',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teaching_and_research_detail',
            name='year_of_completion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
