# Generated by Django 2.2.4 on 2020-02-17 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20200213_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching_and_research_detail',
            name='emoluments',
        ),
        migrations.RemoveField(
            model_name='teaching_and_research_detail',
            name='pay_scale',
        ),
        migrations.RemoveField(
            model_name='teaching_and_research_detail',
            name='role',
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='co_investigators',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='guide',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='name_of_body',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='name_of_institute',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='name_of_student',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='organisation',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='period',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='status_of_membership',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaching_and_research_detail',
            name='year_of_completion',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 17, 21, 19, 56, 398376, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Other_important_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_and_recognition', models.TextField()),
                ('any_other_relevant_information', models.TextField()),
                ('reference', models.TextField()),
                ('statement_of_objective', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_details', to='recruitment.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recruitment.Applicant')),
            ],
        ),
    ]
