# Generated by Django 2.2.24 on 2022-09-24 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20210808_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 24, 20, 31, 47, 549967, tzinfo=utc)),
        ),
    ]
