# Generated by Django 2.2.20 on 2021-05-02 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20210502_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2021, 5, 2, 7, 40, 39, 653830, tzinfo=utc))),
                ('signature', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='books',
            name='supporting_documents',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='supporting_documents',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='educationalqualifications',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='employmentexp',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='general',
            name='reservation_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='newspaperarticle',
            name='supporting_documents',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='researchexp',
            name='supporting_documents',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='seminararticles',
            name='supporting_documents',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 7, 40, 39, 641811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='defence_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 7, 40, 39, 652829, tzinfo=utc)),
        ),
    ]
