# Generated by Django 2.2.20 on 2021-04-24 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20200221_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 16, 6, 46, 11082, tzinfo=utc)),
        ),
    ]
