# Generated by Django 2.2.24 on 2022-09-25 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20220925_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 9, 58, 7, 94587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='general',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
