# Generated by Django 2.2.20 on 2021-04-25 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20210424_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='reservation',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Research_Domain',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 8, 59, 9, 588222, tzinfo=utc)),
        ),
    ]
