# Generated by Django 2.2.20 on 2021-04-25 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20210425_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 17, 45, 41, 872715, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Seminar_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.TextField()),
                ('seminar_subject', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('published', models.TextField()),
                ('duration', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_articles', to='recruitment.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('duration', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_exp', to='recruitment.Applicant')),
            ],
        ),
    ]
