# Generated by Django 2.2.4 on 2021-04-25 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20210425_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('area_of_qualification', models.CharField(max_length=200)),
                ('category_of_university', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('ResultAwaited', 'ResultAwaited'), ('FinalAwaited', 'FinalAwaited'), ('Ongoing', 'Ongoing')], max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='other_important_details',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='professional_detail',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='teaching_and_research_detail',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 11, 44, 44, 445345, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Academic_detail',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Other_important_details',
        ),
        migrations.DeleteModel(
            name='Professional_detail',
        ),
        migrations.DeleteModel(
            name='Teaching_and_research_detail',
        ),
        migrations.AddField(
            model_name='general',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general', to='recruitment.Applicant'),
        ),
    ]
