# Generated by Django 4.2 on 2023-04-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_administrativedetails_id_alter_applicant_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 18, 24, 6, 58014, tzinfo=datetime.timezone.utc)),
        ),
    ]
