# Generated by Django 2.2.20 on 2021-04-26 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20210425_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 3, 34, 38, 909503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research_exp',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seminar_articles',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Newspaper_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.TextField()),
                ('journal_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date_published', models.CharField(max_length=20)),
                ('referred', models.TextField()),
                ('level', models.CharField(max_length=20)),
                ('naas', models.TextField()),
                ('isbn_issn', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_article', to='recruitment.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('date_of_publisher', models.CharField(max_length=100)),
                ('isbn_issn', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='recruitment.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('date_publish', models.CharField(max_length=20)),
                ('isbn', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='recruitment.Applicant')),
            ],
        ),
    ]
