# Generated by Django 2.2.24 on 2023-03-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_administrativedetails_id_alter_applicant_date_and_more'),
        ('recruitment', '0007_auto_20230227_1555'),
    ]

    operations = [
    ]
