# Generated by Django 4.2 on 2023-04-06 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_applicant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 18, 27, 46, 373510, tzinfo=datetime.timezone.utc)),
        ),
    ]
