# Generated by Django 4.2 on 2023-04-06 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_alter_applicant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='mobile_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 19, 34, 4, 528413, tzinfo=datetime.timezone.utc)),
        ),
    ]
