# Generated by Django 2.2.20 on 2021-04-26 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20210426_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research_exp',
            old_name='To',
            new_name='to',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 4, 43, 35, 723949, tzinfo=utc)),
        ),
    ]
