# Generated by Django 4.2 on 2023-04-07 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_general_mobile_code_alter_applicant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 2, 49, 20, 966566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='general',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
