# Generated by Django 4.2 on 2023-04-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_merge_20230310_1647'),
        ('recruitment', '0012_alter_applicant_date_alter_general_dob'),
    ]

    operations = [
    ]
