# Generated by Django 4.2 on 2023-04-18 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_alter_applicant_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='payment_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 4, 33, 12, 824459, tzinfo=datetime.timezone.utc)),
        ),
    ]
