# Generated by Django 4.2 on 2023-04-26 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_declaration_payment_id_alter_applicant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 26, 15, 32, 18, 530511, tzinfo=datetime.timezone.utc)),
        ),
    ]
